---
title: "Random Forest Custom"
output:
      html_document:
        keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rpart) # using the tree implementation of rpart 

data("iris") # Example dataset to demonstrate the use of a random forest

# Define parameters:
number_of_trees = 200
m_of_M = 2 # Number of columns to consider
n = dim(iris)[1]
M = dim(iris)[2]
trees = list()

#Fit forest to data:
#Steps:
for(i in 1:number_of_trees){
  # sample dataset for each tree with replacement (bootstrap sample)
  rows = sample(1:n,size=n,replace=TRUE)  
  
  # sample columns for each tree but with n<M number of total columns
  cols = sample(1:M,size=m_of_M)
  
  # grow tree to largest extend possible (do not prune) and find best split
  baseLearner = rpart(formula = iris$Species ~., data = iris[rows,cols],method = "class")
  
  trees[[i]] = baseLearner
}

```

New dataset (in this case using the same as fit)
```{r}
newdata = iris
n_classes = length(levels(newdata$Species))
n_rows = dim(newdata)[1]
```

Classification prediction using Random Forest (Majority Vote)
```{r}

result = matrix(ncol=n_classes,nrow=n)


#initialize empty result row
result = matrix(data=0,nrow=n_rows,ncol=n_classes)
for (j in 1:number_of_trees){
  curr = predict(trees[[j]],newdata=newdata)
  
  # get maximum column and add a 1 as a vote
  votes = cbind(1:n_rows,max.col(curr,ties.method = 'random'))
  result[votes] = result[votes]+1
  
}
result = as.data.frame(result)

# Get final votes for each observed value
colnames(result) = levels(iris$Species)
votedResults = colnames(result)[max.col(result,ties.method="random")]
print(votedResults)

```


Regression prediction using Random Forest (Mean over all trees for every Value)
```{r}
result = matrix(data=0,nrow=n_rows,ncol=n_classes)
for (j in 1:number_of_trees){
  curr = predict(trees[[j]],newdata=newdata)
  result = result+curr
}
result = result/number_of_trees
print(result)

```